## numpy array creation example array() and print its properties

In [1]:
import numpy as np

In [9]:
def function1():
    a1 = [10,20,30,40,50]
    print(a1)
    print(f"DType = {type(a1)}")
    print(f"a1[0]={type(a1[0])}")
    

In [10]:
function1()

[10, 20, 30, 40, 50]
DType = <class 'list'>
a1[0]=<class 'int'>


In [14]:
def function2():
    n_array=np.array([11,22,33,44,55])
    print(n_array)
    print(f"Type={type(n_array)}")

In [15]:
function2()

[11 22 33 44 55]
Type=<class 'numpy.ndarray'>


In [28]:
def function3():
    arr=np.array([10,20,30,40,50,60])
    print(arr)

    print(f"Type = {type(arr)}")
    print(f"DType = {arr.dtype}")
    print(f"Item size= {arr.itemsize}")
    print(f"Size = {arr.size}")
    print(f"NDIM = {arr.ndim}")
    print(f"NBYTES = {arr.nbytes}")

In [29]:
function3()

[10 20 30 40 50 60]
Type = <class 'numpy.ndarray'>
DType = int64
Item size= 8
Size = 6
NDIM = 1
NBYTES = 48


In [35]:
arr=np.array([10,20,30,40,50,60])
print(arr)

[10 20 30 40 50 60]


In [40]:
def printProperties(arr):
    print(arr)
    print(f"Type = {type(arr)}")
    print(f"DType = {arr.dtype}")
    print(f"Item size= {arr.itemsize}")
    print(f"Size = {arr.size}")
    print(f"NDIM = {arr.ndim}")
    print(f"NBYTES = {arr.nbytes}")

n1 =np.array([11,22,33,44,55])
printProperties(n1)
    
    

[11 22 33 44 55]
Type = <class 'numpy.ndarray'>
DType = int64
Item size= 8
Size = 5
NDIM = 1
NBYTES = 40


In [41]:
printProperties(arr)

[10 20 30 40 50 60]
Type = <class 'numpy.ndarray'>
DType = int64
Item size= 8
Size = 6
NDIM = 1
NBYTES = 48


In [44]:
n2=np.array([11,22,33],dtype=np.int32)
printProperties(n2)

[11 22 33]
Type = <class 'numpy.ndarray'>
DType = int32
Item size= 4
Size = 3
NDIM = 1
NBYTES = 12


In [45]:
n4=np.array([11.2,34.5,46.7,3.8])
printProperties(n4)

[11.2 34.5 46.7  3.8]
Type = <class 'numpy.ndarray'>
DType = float64
Item size= 8
Size = 4
NDIM = 1
NBYTES = 32


In [46]:
n5=np.array(["C","C++","Python","Java"])
printProperties(n5)

['C' 'C++' 'Python' 'Java']
Type = <class 'numpy.ndarray'>
DType = <U6
Item size= 24
Size = 4
NDIM = 1
NBYTES = 96
